version: '3'
services:
  db:
    build:
      context: ./../db/
    ports:
       - "5432:5432"
    env_file: ./../common/credentials/db.env

  server:
    build:
      context: ./../server/
    depends_on:
      - db
    ports:
       - "7700:5005"
    env_file: ./../common/credentials/db.env
    environment:
        INFLUSS_DB_HOST: db
        INFLUSS_DB_PORT: 5432

  frontend-web-typescript:
    build:
      context: ./../frontend/web-typescript/
    depends_on:
      - server
    ports:
       - "7701:80"
    env_file: ./../common/credentials/db.env
    environment:
        INFLUSS_SERVER_EXTERNAL_API_HOST: localhost
        INFLUSS_SERVER_EXTERNAL_API_PORT: 7700
        INFLUSS_FRONTEND_1_PORT: 7701
